language: php
php:
  - nightly
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - $HOME/.composer/cache/files
install:
  - composer install --ignore-platform-reqs
script:
  - vendor/bin/phpunit tests
