language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install
script:
  - vendor/bin/phpunit tests --bootstrap vendor/autoload.php --coverage-clover reports/coverage/clover.xml --whitelist src
  - vendor/bin/test-reporter --coverage-report reports/coverage/clover.xml
